---
title: "NeCSA Vertical (Tidy Data)"
author: "Marina Schnell"
date: "2024-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library(readxl)
```

```{r load-data}

# skipped 2017 (location in transect recorded in increments of 10 (cm?), and for T1 and T2 there are blanks next to the location numbers, and in T3 the location is blank for the last of the recorded species)

# skipped 2018 (didn't do transect 1, and there was no ending measurement)

vertical2019_1 <- read_excel("data/2019_verticalWEST_MDR_NeCSA.xlsx", range = "F6:H61")
vertical2019_2 <- read_excel("data/2019_verticalWEST_MDR_NeCSA.xlsx", range = "J6:L124")
vertical2019_3 <- read_excel("data/2019_verticalWEST_MDR_NeCSA.xlsx", range = "N6:P53")

vertical2020_1 <- read_excel("data/2020_verticalWEST_MDR_NeCSA.xlsx", range = "F6:H104")
vertical2020_2 <- read_excel("data/2020_verticalWEST_MDR_NeCSA.xlsx", range = "J6:L193")
vertical2020_3 <- read_excel("data/2020_verticalWEST_MDR_NeCSA.xlsx", range = "N6:P188")

vertical2021_1A <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "F6:H50",
                              sheet = "Transect 1")
vertical2021_1B <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "J6:L50",
                              sheet = "Transect 1")
vertical2021_1C <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "N6:P47",
                              sheet = "Transect 1")

vertical2021_2A <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "F6:H50",
                              sheet = "Transect 2")
vertical2021_2B <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "J6:L240",
                              sheet = "Transect 2")
vertical2021_2C <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "N6:P247",
                              sheet = "Transect 2")

vertical2021_3A <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "F6:H50",
                              sheet = "Transect 3")
vertical2021_3B <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "J6:L240",
                              sheet = "Transect 3")
vertical2021_3C <- read_excel("data/2021_vertical_MDR_NeCSA.xlsx", range = "N6:P247",
                              sheet = "Transect 3")


vertical2022_1 <- read_excel("data/2022_vertical_MDR_NeCSA.xlsx", range = "F6:H150")
vertical2022_2 <- read_excel("data/2022_vertical_MDR_NeCSA.xlsx", range = "J6:L240")
vertical2022_3 <- read_excel("data/2022_vertical_MDR_NeCSA.xlsx", range = "N6:P247")

vertical2023_1 <- read_excel("data/2023_vertical_MDR_NeCSA.xlsx", range = "F6:H147")
vertical2023_2 <- read_excel("data/2023_vertical_MDR_NeCSA.xlsx", range = "J6:L202")
vertical2023_3 <- read_excel("data/2023_vertical_MDR_NeCSA.xlsx", range = "N6:P161")

```

```{r tidy-data-2019}
vertical2019_1 <- vertical2019_1 %>%
  mutate(transect = 1)

vertical2019_2 <- vertical2019_2 %>%
  mutate(transect = 2)

vertical2019_3 <- vertical2019_3 %>%
  mutate(transect = 3)

vertical2019 <- full_join(vertical2019_1, vertical2019_2) %>% 
  full_join(vertical2019_3) %>% 
  rename(species = "Species Code",
         start = "Start distance from 0 (m)",
         end = "End distance (m)") %>%
  mutate(distance = end - start) %>%
  relocate(transect, .before = species) %>%
  mutate(species = case_when(species == "FD" ~ "Fspp",
                             species == "FV" ~ "Fspp",
                             species == "FS" ~ "Fspp",
                             TRUE ~ species)) %>%
  mutate(year = 2019) %>%
  relocate(year, .before = transect)
  

```

```{r tidy-data-2020}

### WARNING: it looks like these are listed in reverse order (starting at low tide mark)
# ALSO missing species codes for first part of transect 3
# ask Tanya about this

vertical2020_1 <- vertical2020_1 %>%
  mutate(transect = 1)

vertical2020_2 <- vertical2020_2 %>%
  mutate(transect = 2) %>%
  rename("End distance (cm)" = "End distance (Cm)")

vertical2020_3 <- vertical2020_3 %>%
  mutate(transect = 3) %>%
  rename("End distance (cm)" = "End distance (Cm)")

vertical2020 <- full_join(vertical2020_1, vertical2020_2) %>% 
  full_join(vertical2020_3) %>% 
  rename(species = "Species Code",
         start = "Start distance from 0 (m)",
         end = "End distance (cm)") %>%
  mutate(start = start/100) %>%
  mutate(end = end/100) %>%
  mutate(distance = end - start) %>%
  relocate(transect, .before = species) %>%
  mutate(species = case_when(species == "FD" ~ "Fspp",
                             species == "FV" ~ "Fspp",
                             species == "FS" ~ "Fspp",
                             TRUE ~ species)) %>%
  mutate(year = 2020) %>%
  relocate(year, .before = transect)

```

```{r tidy-data-2021}
vertical2021_1 <- full_join(vertical2021_1A, vertical2021_1B) %>%
  full_join(vertical2021_1C) %>%
  mutate(transect = 1)

vertical2021_2 <- full_join(vertical2021_2A, vertical2021_2B) %>%
  full_join(vertical2021_2C) %>%
  mutate(transect = 2)

vertical2021_3 <- full_join(vertical2021_3A, vertical2021_3B) %>%
  full_join(vertical2021_3C) %>%
  mutate(transect = 3)

vertical2021 <- full_join(vertical2021_1, vertical2021_2) %>% 
  full_join(vertical2021_3) %>% 
  rename(species = "Species Code",
         start = "Start distance from 0 (m)",
         end = "End distance (m)") %>%
  mutate(distance = end - start) %>%
  relocate(transect, .before = species) %>%
  mutate(species = case_when(species == "FD" ~ "Fspp",
                             species == "FV" ~ "Fspp",
                             species == "FS" ~ "Fspp",
                             TRUE ~ species)) %>%
  mutate(year = 2021) %>%
  relocate(year, .before = transect)

```

```{r tidy-data-2022}
vertical2022_1 <- vertical2022_1 %>%
  mutate(transect = 1)

vertical2022_2 <- vertical2022_2 %>%
  mutate(transect = 2)

vertical2022_3 <- vertical2022_3 %>%
  mutate(transect = 3)

vertical2022 <- full_join(vertical2022_1, vertical2022_2) %>% 
  full_join(vertical2022_3) %>% 
  rename(species = "Species Code",
         start = "Start distance from 0 (m)",
         end = "End distance (m)") %>%
  mutate(distance = end - start) %>%
  relocate(transect, .before = species) %>%
  mutate(species = case_when(species == "FD" ~ "Fspp",
                             species == "FV" ~ "Fspp",
                             species == "FS" ~ "Fspp",
                             TRUE ~ species)) %>%
  mutate(year = 2022) %>%
  relocate(year, .before = transect)

```

```{r tidy-data-2023}
vertical2023_1 <- vertical2023_1 %>%
  mutate(transect = 1)

vertical2023_2 <- vertical2023_2 %>%
  mutate(transect = 2)

vertical2023_3 <- vertical2023_3 %>%
  mutate(transect = 3)

vertical2023 <- full_join(vertical2023_1, vertical2023_2) %>% 
  full_join(vertical2023_3) %>% 
  rename(species = "Species Code",
         start = "Start distance from 0 (m)",
         end = "End distance (m)") %>%
  mutate(distance = end - start) %>%
  relocate(transect, .before = species) %>%
  mutate(species = case_when(species == "FD" ~ "Fspp",
                             species == "FV" ~ "Fspp",
                             species == "FS" ~ "Fspp",
                             TRUE ~ species)) %>%
  mutate(year = 2023) %>%
  relocate(year, .before = transect)

```

```{r join everything}
vertical_all <- full_join(vertical2019, vertical2020) %>%
  full_join(vertical2021) %>%
  full_join(vertical2022) %>%
  full_join(vertical2023) %>%
  mutate(year = as.factor(year))

write_csv(vertical_all, "data/vertical_all.csv")

```