---
title: "NeCSA Horizontal 2018 (Tidy Data)"
author: "Marina Schnell"
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library(readxl)
```

```{r load-previous-data}

expanded_seaweeds_mdr <- read.csv("data/expanded_seaweeds_mdr.csv")

```

```{r load-2018-data}

# not tidying invert data because they didn't identify Littorina snails to species

# low quadrats

L00_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "A12:C28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 0,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L03_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "D12:F28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 3,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L06_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "G12:I28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 6,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L09_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "J12:L28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 9,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L12_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "M12:O28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 12,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L15_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "P12:R28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 15,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L18_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "S12:U28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 18,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L21_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "V12:X28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 21,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L24_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "Y12:AA28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 24,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

L27_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "AB12:AD28") %>%
  mutate(tide_ht = "L",
         quadrat_m = 27,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)


# mid quadrats

M00_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "A12:B28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 0)

M03_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "D12:E28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 3)

M06_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "G12:H28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 6)

M09_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "J12:K28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 9)

M12_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "M12:N28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 12)

M15_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "P12:Q28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 15)

M18_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "S12:T28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 18)

M21_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "V12:W28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 21)

M24_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "Y12:Z28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 24)

M27_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Mid", range = "AB12:AC28") %>%
  mutate(tide_ht = "M",
         quadrat_m = 27)


# high quadrats

H00_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "A12:C28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 0,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H03_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "D12:F28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 3,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H06_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "G12:I28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 6,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H09_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "J12:L28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 9,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H12_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "M12:O28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 12,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H15_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "P12:R28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 15,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H18_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "S12:U28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 18,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H21_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "V12:X28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 21,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H24_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "Y12:AA28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 24,
         `# of squares/25` = NULL) %>%
  rename(`# of squares/25` = 2)

H27_2018 <- read_excel("data/2018_full_NeCSA.xlsx",
                       sheet = "West HT Low", range = "AB12:AD28") %>%
  mutate(tide_ht = "H",
         quadrat_m = 27)


```

```{r join-all-seaweeds}

L_seaweeds_2018 <- full_join(L00_2018, L03_2018) %>%
  full_join(L06_2018) %>%
  full_join(L09_2018) %>%
  full_join(L12_2018) %>%
  full_join(L15_2018) %>%
  full_join(L18_2018) %>%
  full_join(L21_2018) %>%
  full_join(L24_2018) %>%
  full_join(L27_2018)
  
M_seaweeds_2018 <- full_join(M00_2018, M03_2018) %>%
  full_join(M06_2018) %>%
  full_join(M09_2018) %>%
  full_join(M12_2018) %>%
  full_join(M15_2018) %>%
  full_join(M18_2018) %>%
  full_join(M21_2018) %>%
  full_join(M24_2018) %>%
  full_join(M27_2018)

H_seaweeds_2018 <- full_join(H00_2018, H03_2018) %>%
  full_join(H06_2018) %>%
  full_join(H09_2018) %>%
  full_join(H12_2018) %>%
  full_join(H15_2018) %>%
  full_join(H18_2018) %>%
  full_join(H21_2018) %>%
  full_join(H24_2018) %>%
  full_join(H27_2018)

seaweeds_2018 <- full_join(L_seaweeds_2018, M_seaweeds_2018) %>%
  full_join(H_seaweeds_2018) %>%
  rename(seaweed_simple = `Substrata % Cover`,
         squares_out_of_25 = `# of squares/25`) %>%
  mutate(squares_out_of_25 = case_when(is.na(squares_out_of_25) ~ 0,
                                       TRUE ~ squares_out_of_25),
         proportion = squares_out_of_25/25,
         year = 2018,
         `...3` = NULL) %>%
  mutate(seaweed_simple = case_when(seaweed_simple == "Ascophyllum" ~ "Asco_n",
                                     seaweed_simple == "Ceramium" ~ "Cera_r",
                                     seaweed_simple == "Chondrus crispus" ~ "Chon_c",
                                     seaweed_simple == "Corallina oficianalis"~ "Cora_o",
                                     seaweed_simple == "Elachista fucicola" ~ "Elac_f",
                                     seaweed_simple == "Enteromorpha" ~ "Ente_sp",
                                     seaweed_simple == "F. distichus" ~ "Fucu_spp",
                                     seaweed_simple == "F. spiralis" ~ "Fucu_spp",
                                     seaweed_simple == "F. vesiculosus" ~ "Fucu_spp",
                                     seaweed_simple == "Laminaria sp." ~ "Lami_sp",
                                     seaweed_simple == "Mastocarpus" ~ "Mast_s",
                                     seaweed_simple == "Polysiphonia lanosa" ~ "Vert_l",
                                     seaweed_simple == "Porphyra sp." ~ "Porp_sp",
                                     seaweed_simple == "Poryphyra sp." ~ "Porp_sp",
                                     seaweed_simple == "Red algae" ~ "RED",
                                     seaweed_simple == "Spongomorpha" ~ "Spon_sp",
                                     seaweed_simple == "Ulva lactuca" ~ "Ulva_l",
                                     seaweed_simple == "other" ~ "other",
                                     TRUE ~ seaweed_simple
                                     )) %>%
  filter(!is.na(seaweed_simple))

#distinct(seaweeds_2018, seaweed_simple) %>%
#  arrange(seaweed_simple)

```

```{r join-and-expand-and-join}

expanded_seaweeds_mdr <- expanded_seaweeds_mdr %>%
  mutate(seaweed_simple = case_when(grepl("Fucu", seaweed_species) ~ "Fucu_spp",
                                    TRUE ~ seaweed_species)) %>%
  mutate(seaweed_simple = gsub("CC", "", seaweed_simple)) %>%
  mutate(seaweed_simple = gsub("SC", "", seaweed_simple))

seaweeds_mdr <- full_join(expanded_seaweeds_mdr, seaweeds_2018)


expanded_seaweeds_mdr_with_2018 <- expand(seaweeds_mdr,
                                          year,
                                          tide_ht,
                                          quadrat_m,
                                          seaweed_simple) %>%
  left_join(seaweeds_mdr,
            by = join_by(year, tide_ht, quadrat_m, seaweed_simple)) %>%
  mutate(squares_out_of_25 = replace_na(squares_out_of_25, 0)) %>%
  mutate(proportion = replace_na(proportion, 0)) %>%
  mutate(proportion_new = case_when(seaweed_simple == "Ulva_l" & tide_ht == "H" ~ 0,
                                    TRUE ~ proportion)) %>%
  mutate(proportion_new = replace_na(proportion_new, 0))

write_csv(expanded_seaweeds_mdr_with_2018, "C:/Users/Marina/Desktop/Repositories/MDR-NeCSA-2024/data/expanded_seaweeds_mdr_with_2018.csv")

```